### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by DCNick3**
I want to try to work on NCA decryption, so cleaning up bitrot felt like a logical first step.

Some of the dependencies (most notably - the RustCrypto ones) have changed & reorganized quite a bit, requiring some changes.

`elf` seems to have changed very dramatically. I am not interested (and, honestly, qualified) in NRO generation stuff it is used for, so it's the only out-of-date dep after these changes.

Notably, there is a breaking change, as `BlockModeError` type is non-existent now. I removed the `Error` variant for it.

### CODE REVIEW

**Comment by roblabla** [comment]
Oh man, this is awesome, thanks a bunch for this!

I should probably set up dependabot for linkle, so I can catch those breaking changes as they come.

I just ran the tests, there are some things that need to be fixed in cargo-nro. As for [the `cargo-deny` failure](https://github.com/MegatonHammer/linkle/actions/runs/3867301148/jobs/6592257973#step:4:52), it's complaining about license problems, specifically the `Unicode-DFS-2016` not being in the license allowlist [here](https://github.com/MegatonHammer/linkle/blob/master/deny.toml#L12). I just checked, that license is essentially MIT for unicode data files, so it's fine to depend on it! Could you add it to the deny.toml?

**Comment by DCNick3** [comment]
>there are some things that need to be fixed in cargo-nro

Ah, shoot, I was only compiling `linkle_clap` it seems.

>re:cargo-deny

Sure thing

**Comment by DCNick3** [comment]
> `ansi_term` and `atty` used by `structopt` are unmaintained

*sigh*

**Comment by roblabla** [comment]
Hmm, crap, cargo-deny is complaining about ansi_term being unmaintained. Sucks. We'd need to migrate `linkle_clap` from structopt to clap's built-in derive macro in clap v4.

If that's too much work for you, we can just ignore that advisory for now, and I'll take care of doing the update sometime over the next week-end. You can add the following to the deny.toml under the `[advisories]` section to silence the deny.toml error:

```
ignore = [
  "RUSTSEC-2021-0139"
]
```

**Comment by DCNick3** [comment]
ig I can fix those clippy issues too while I am at it

**Comment by roblabla** [comment]
For the dead code, you can probably add an `#[allow]` on those fields. I think they're only ever read during deserialization of the keyset, but since we don't have NCA decryption in linkle yet, they're unused.

**Comment by roblabla** [comment]
Awesome. Thanks a lot :)

**Pull request merged**
